sudo: false
language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
env:
  - PREFER_LOWEST="--prefer-lowest --prefer-stable"
  - PREFER_LOWEST=""
matrix:
  fast_finish: true
  allow_failures:
     - php: nightly
before_script:
  - yes '' | pecl install -f mongodb-1.4.3
  - composer update $PREFER_LOWEST
script:
  - ./vendor/bin/phing
after_success: ./vendor/bin/php-coveralls -v
